use rxjs
sharapinski/angular-program pull request #7
Opened 2018-01-13 08:19 UTC by sharapinski

1. changed 'course.service.ts' to Observables. 
2. added a filter in 'course.service.ts'
3. done in #2 
4. used replay subject in 'auth.service.ts'
5. skiped???
6. skiped

2018-01-15 13:57 UTC, Antontelesh requested changes
Please, apply the necessary changes and then merge

2018-01-15 13:57 UTC, Antontelesh commented on src/app/app.component.ts
> +    this._subscription.unsubscribe();
and where `this._subscription` is defined?

2018-01-15 13:57 UTC, Antontelesh commented on src/app/app.component.ts
> +  _subscription: any;
`this._subscription` is not of type `any`, but of type `Subscription` which can be imported from `rxjs/Subscription`

2018-01-15 13:57 UTC, Antontelesh commented on src/app/shared/course.service.ts
> +                    .map(list => list.filter(course => Number(course.date) > new Date().getTime() - 14 * 24 * 60 * 1000))
please, move this to component that accepts `Observable<Course[]>`

2018-01-15 13:57 UTC, Antontelesh commented on src/app/pages/course-list/course-list.component.ts
> +      this._service.removeItem(item).subscribe(res => {
it's bad to subscribe to an observable than never ends. you introduce memory leaks by doing this.
it's better to call removeItem() and treat this as an effect.
the service should be responsible for emitting a new updated array of courses in the main stream.

2018-01-22 17:43 UTC, sharapinski commented on src/app/app.component.ts
> +  _subscription: any;
ok

2018-01-22 17:45 UTC, closed without merging